//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banq_desu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banqEntities : DbContext
    {
        public banqEntities()
            : base("name=banqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KARTY> KARTY { get; set; }
        public virtual DbSet<KLIENCI> KLIENCI { get; set; }
        public virtual DbSet<KONTA> KONTA { get; set; }
        public virtual DbSet<KREDYTY> KREDYTY { get; set; }
        public virtual DbSet<TRANSAKCJE> TRANSAKCJE { get; set; }
    }
}
