//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banq_desu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARTY
    {
        public int id { get; set; }
        public int numer { get; set; }
        public System.DateTime data_waznosci { get; set; }
        public string rodzaj { get; set; }
        public int id_konta { get; set; }
    
        public virtual KONTA KONTA { get; set; }
    }
}
