//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banq_desu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTA()
        {
            this.KARTY = new HashSet<KARTY>();
            this.TRANSAKCJE = new HashSet<TRANSAKCJE>();
            this.TRANSAKCJE1 = new HashSet<TRANSAKCJE>();
        }
    
        public int id { get; set; }
        public int nr_konta { get; set; }
        public string rodzaj { get; set; }
        public decimal saldo { get; set; }
        public int id_klienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARTY> KARTY { get; set; }
        public virtual KLIENCI KLIENCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAKCJE> TRANSAKCJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSAKCJE> TRANSAKCJE1 { get; set; }
    }
}
