//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banq_desu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KREDYTY
    {
        public int id { get; set; }
        public System.DateTime data_pobrania { get; set; }
        public int nr_umowy { get; set; }
        public decimal przyznana_kwota { get; set; }
        public decimal pozostala_kwota { get; set; }
        public int liczba_rat { get; set; }
        public decimal oprocentowanie { get; set; }
        public decimal kwota_raty { get; set; }
        public System.DateTime data_splaty { get; set; }
        public int id_klienta { get; set; }
    
        public virtual KLIENCI KLIENCI { get; set; }
    }
}
