//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banq_desu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSAKCJE
    {
        public int id { get; set; }
        public string waluta { get; set; }
        public decimal kwota { get; set; }
        public System.DateTime data { get; set; }
        public int nadawca { get; set; }
        public int odbiorca { get; set; }
        public string tytul { get; set; }
    
        public virtual KONTA KONTA { get; set; }
        public virtual KONTA KONTA1 { get; set; }
    }
}
